### ISSUE TITLE
ESP code conver to Arduino Uno code

### ISSUE THREAD

**Issue by Rorschac** [stuartpittaway/diyBMS#10]
Hi, I want to convert "ESP test" code  to arduino uno code. I have removed some code lines specified for ESP8266, and I compiled with any problem for Arduino uno.  Now, I have tested this code that i send "X" from serial interface. I see the message on I2C, but attiny85 did not response.  I added scope screen and lines that i removed from code.

```
extern "C"
{
  #include "user_interface.h"
}

os_timer_t myTimer;

//  os_timer_setfn(&myTimer, timerCallback, NULL);
//  os_timer_arm(&myTimer, 1000, true);
```
![img_20180716_144551](https://user-images.githubusercontent.com/25567370/42760717-fce3cb54-8913-11e8-969d-aeabc598b5ff.jpg)

**Comment by tvixen** [comment]
Hi there
If it helps, you can have a look at my code. 
I converted it into a Arduino Nano :+1:   https://github.com/tvixen/diy-BMS-with-Arduino-Nano

Br Tim

**Comment by chickey** [comment]
Have you burnt the fuses on the attiny85?

**Comment by Rorschac** [comment]
Yes. I designed my own board with altium based on orginal schematic and component for product PCB at home. I want to share this design if I can run it. I bootloaded orginal code in fourteen attiny85. Just I changed ESP code for load uno or mega. I can send message with uno on I2C but no response attiny85 board.

**Comment by chickey** [comment]
Ok asking as I had no luck initially and had to increase the stretch clock from 1000 to 2500 as memory serves as I couldn’t get any communication either but I hadn’t set the fuses so the speed etc was incorrect and the stretchclock increase kind of masked the issue.

**Comment by tvixen** [comment]
You can use Stuart's slave software, and then try mine for your master (UNO) This should work.

**Comment by Rorschac** [comment]
I used your code but no difference. Uno sends but attiny85 not talk. I see the signal at the output of ADUM but attiny is not talk.

**Comment by Merdeka** [comment]
Haven't tested it but could it be an issue with the default i2c bus speed? 100khz vs 400kHz.

Cheers,
Timo

**Comment by Rorschac** [comment]
I found a ESP8266 and used the orginal code, original bus speed. It doesn't work too. Attiny85 doesn't reponse again. I controlled everything on pcb. It seems normal. I don't know why not running it?

**Comment by tvixen** [comment]
Do you see the green diode blink on the Cell_module. If not, check your programming of the ATTiny85.

**Comment by tvixen** [comment]
If you use Uno, you don't have to use Optiboot. As it's only Nano having a problem with the watchdog.

**Comment by tvixen** [comment]
Try ONLY to connect one module to the bus. When this is working, add another. aso aso.

**Comment by chickey** [comment]
Also try the clock stretch change

**Comment by Rorschac** [comment]
Led is not blinking. But I saw a video on youtube, diyBMS tutorial it haven't blinking too. Already I'm working with only one cell.  Also I controlled reset pin voltage, it's almost 2V.

https://www.youtube.com/watch?v=ZahB-86zzfQ

**Comment by chickey** [comment]
https://youtu.be/CbuOteAcv04

**Comment by Rorschac** [comment]
Thanks, I have watched video now.  I guess, your github code have all changes from your video. I will try now.

**Comment by Rorschac** [comment]
Did you added 2.2K pull-up resistors to esp I2C wire, except modul?

**Comment by tvixen** [comment]
Yes this is very important to do. If not, there's no 'power' to feed the bus.

**Comment by Rorschac** [comment]
I loaded Colin's codes. SCK does not seem normal, does it? It's a bit short.


Scope1-SCK
Scope2-SDA

![scope1](https://user-images.githubusercontent.com/25567370/42876685-1dbfe592-8a90-11e8-9ae7-f30177835344.jpg)

**Comment by chickey** [comment]
Module code should be identical and I backed out the stretch clock changes in the controller code.  I more put the video to show the issues I had as I hadn’t done the fuses etc

**Comment by Rorschac** [comment]
Is it possible to communicate with the scope as it looks? As a result, everybody have worked. Should I search the fault somewhere else? I know I'm starting to get boring, I'm sorry for that but I need help.

**Comment by Rorschac** [comment]
There is a warning in the code. Could the factory have set for external crystal?
Because the module does not work even in the simplest code like led blink.

`If you burn incorrect fuses to ATTINY85 you may need to connect a crystal over the pins to make it work again!`

**Comment by Rorschac** [comment]
I found something like this. I hope this is the problem.
[](http://www.instructables.com/id/Simple-and-cheap-Fuse-Doctor-for-Attiny)

**Comment by Rorschac** [comment]
I have a good and bad news for you. The good news is that the problem is solved, the bad news is that I think the bootloading code is loading. I hit the upload button and the problem is solved. And Colin, your arrangements are wonderful. I thank you all very much.
