### ISSUE TITLE
Not compiling under Linux

### ISSUE THREAD

**Issue by delboy711** [stuartpittaway/diyBMS#12]
While waiting for my diyBMS boards to arrive from China I checked to make sure the code compiled.

Under Linux I found Arduino-ESP8266-BMS-Controller.ino does not compile because  line 39
#include "softap.h" has incorrect capitalization.
Line 4 in SoftAP.cpp has the same problem.

Looking forward to getting to grips with this project. I intend to try running it on an ESP32 if possible since I would like to incorporate the BMS function on the same controller as battery charge/discharge rate control, and need the extra pins of an ESP32.

**Comment by stuartpittaway** [comment]
Fixed, thanks.
