### ISSUE TITLE
Qi Charger for DC/DC Isolation and Dump Load?

### ISSUE THREAD

**Issue by jamestutton** [stuartpittaway/diyBMS#13]
Hi have an idea and wanted to float it here as know there a few makers using this project who might be willing to test it out and don't have time nor facilities to test it myself right now.

So as you can see from the topic the idea is a Qi charger as far as my understanding goes Qi provides ~5W of DC/DC isloation. So the concept is rather than (or as well as) a DUMP resistor why not have a QI Charger and receiver to bypass power to the next pack.  In its simplest form this could be:

**PACK 1:** 
MOSFET -> 5V boost circuit to USB port-> Qi plate 
_()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()  **Isolation** _
**PACK2:**
Qi Receiver -> TP4056 Battery -> Batteries

Am I onto something or is there something fundamental I'm missing with this concept. Know the losses would be high but a load resistor is 100% loss so figure even high losses could still be worthwhile.
Aware there are dedicated Isolated DC/DC convertors but most seem to be low power (<2W) and the ICs seem to be more expensive per W that QI.

**Comment by stuartpittaway** [comment]
This might be possible, but isn't really part of this project.
