### ISSUE TITLE
DIY BMS Stencil for 3D printing

### ISSUE THREAD

**Issue by PapaStauth** [stuartpittaway/diyBMS#17]
[DIY BMS Stencil.zip](https://github.com/stuartpittaway/diyBMS/files/2691789/DIY.BMS.Stencil.zip)
Stencil attached to screen the solder paste to your PCB.
From http://solder-stencil.me/
Using *.GM1 and *.GTS files
Using 0.25 mm layer height
Including a 1.2 mm stencil ledge for indexing

**Comment by stuartpittaway** [comment]
Thanks for the stencil.  You can also order these via the PCB company like JLCPCB or ALLPCB
