### ISSUE TITLE
ADUM1251 footprint slightly too wide

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMS#2]
ADUM1251 footprint is SOIC-8-N which appears too wide but will just make electrical contact as it is (just!)

**Comment by chickey** [comment]
I’ll have to check which I ordered 😨

**Comment by stuartpittaway** [comment]
If you get the chip dead centre there is enough contact for the solder, but its tight!

**Comment by stuartpittaway** [comment]
Fixed in latest PCB layout
