### ISSUE TITLE
ATTiny acting weird

### ISSUE THREAD

**Issue by fjgaston** [stuartpittaway/diyBMS#24]
Hi,
I just made my first module board and I started experimenting with it.
I burnt the bootloader and uploaded the code with the Arduino IDE and then I was able to read the voltage of the battery via I2C with my esp32 (I'm still waiting for my ESP8266).
Then the next day, I wasn't able to read the voltage and I wasn't even able to upload any program to the ATTiny "Yikes!  Invalid device signature". 
I investigated what could be wrong, the reset pin is 2.1V, it should be enough. When I de-solder the ATTiny85 I'm able to burn the bootloader or upload programs so it seems like the problem is in the board.
When I power it, the green led blinks once then 2 seconds later the green led turns on and stays on.
I can't figure out what's wrong and the strange thing is that it was working very well yesterday.

**Comment by stuartpittaway** [comment]
Hello, this could be many things, I'd suggest:

1. Check wiring on the ISP header and pins
2. Check for solder bridges between pins on the ATTINY
3. Check you run "burn bootloader" against the attiny with the correct settings (this burns the fuses)
4. Ensure you never select an external crystal on the Arduino menu
