### ISSUE TITLE
When was R5 removed?

### ISSUE THREAD

**Issue by Alpha-IT-Centre** [stuartpittaway/diyBMS#31]
I had boards fabricated and they have in the top left R7, R6, R5. But on the kicad file it has no R5, which version was this removed in, the board I have has V3.0 (Sep 2018) on it.

**Comment by stuartpittaway** [comment]
R5 can be replaced with a jumper wire across the two pins it was left over from a previous design

**Comment by DavidBTB** [comment]
On the BMS cell module schematic off, R5 is 47k and part of the voltage divider. Is that wrong?

**Comment by stuartpittaway** [comment]
The pdf is out of date.
