### ISSUE TITLE
Missing R5 from BOM

### ISSUE THREAD

**Issue by jchengz** [stuartpittaway/diyBMS#33]
https://github.com/stuartpittaway/diyBMS/blob/fbb3a6768bcf161922cc269b395a237fadc689d8/BMS-Cell-Module-Circuit/BMS_Cell_Module_BOM.html#L184

**Comment by stuartpittaway** [comment]
I don't recommend diybms v3 for new builds - use the v4 instead

https://github.com/stuartpittaway/diyBMSv4
