### ISSUE TITLE
Change capacitors to 1206 SMD sizes

### ISSUE THREAD

**Issue by stuartpittaway** [stuartpittaway/diyBMS#4]
Change capacitors to 1206 SMD sizes instead of 1210 as these are easier to find/buy in 0.1 and 1uF sizes.

**Comment by chickey** [comment]
Ah thanks i'll see what i've got in, i have some but i think they are 0603, might just order some more from farnell.

**Comment by stuartpittaway** [comment]
Ordered a bunch from good old AliExpress but thats going to take a few weeks to turn up!

**Comment by stuartpittaway** [comment]
Fixed on latest version of PCB
