### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by tvixen** [stuartpittaway/diyBMS#7]
Hi Stuart
Thanks for this great project..... 
Would it be possible for you to write some documentation.

How it shall work, incl. status of the green led blink ... what to do on the webpage, and the functions in here. (manual calibration aso... )

Thanks in advance
Tim

**Comment by chickey** [comment]
https://www.youtube.com/playlist?list=PLiYbY8lzAN-2qB9rR0Sc7Z7sUrsgYzsiV

Hi Tim,  I did a short video series on the BMS.

Col

**Comment by tvixen** [comment]
ahh super i'll have a look. Thanks mate.
