### ISSUE TITLE
The direction of ALUM1250 

### ISSUE THREAD

**Issue by tvixen** [stuartpittaway/diyBMS#8]
Hi Stuard
I have had a closer look at your diagram, and it seems to me that you have turned the ic2(ALUM1250) 180 degrees around. The datasheet says that the pins to the I2C BUS should be 8,7,6,5 But you have used 1,2,3,4..... what was the reason to do that ?

 (http://www.analog.com/media/en/technical-documentation/data-sheets/ADUM1250_1251.pdf   
  ....  page 11)

Br Tim

**Comment by stuartpittaway** [comment]
Hi Tim, in the situation of this circuit where both sides of the i2c bus are communicated with processors which are i2c compatible (not compliant) it doesn't really matter which way around the comms is.

The spec sheet mentions that "Side 2 of the ADuM1250/ADuM1251 is I2C compliant, whereas Side 1 is only I2C compatible" which would be important if side 2 needed to be i2c compliant - but in this scenario it doesn't.

**Comment by tvixen** [comment]
Hmm, well I still think this could be a issue, as you can pull 10 times more power from side2 (with all the slaves) + the 2K2 on side1 is is way to high.  As I read the specs, they should be 1K when using 100n as C4  ;o) 
Any way, you have done a great job, but I think I will give it a try, turning it the right way, in my next print layout. 

Br Tim

**Comment by stuartpittaway** [comment]
That's the beauty of GitHub, happy to accept a pull request with the fixes/changes. Thanks

**Comment by tvixen** [comment]
Hi Stuard
I would be glad to, but im using Eagle and your using Kidcad.... I think this will be a miss match of different files, and confusion for the users.

Br Tim

**Comment by stuartpittaway** [comment]
Agreed, so you are starting a new project then?

**Comment by tvixen** [comment]
Well the project are already 99% done. and I'm doing the final work tonight. Then order a new set of PCB's, and then test them. So I don't know if I'm gonna write it on github.... seems as a good idea, but I have never done it before so I don't really know how to start :o/ 

Br Tim

**Comment by tvixen** [comment]
Now you've got me started :D ... 
https://github.com/tvixen/diy-BMS-with-Arduino-Nano

**Comment by stuartpittaway** [comment]
Just a comment on the 2k2 resistor on the i2c bus - the spec does mention the lowest resistor should be 1k, however as there is only 1 item on this side of the i2c bus (the ATTINY chip) then the capacitance of the bus will be fine.  The resistor on the other side of the bus should be 1k to the NodeMCU.

No reason not to make it 1k, but it does work as it is.

**Comment by tvixen** [comment]
I don't think the capacitance of the bus on the ATTiny chip side, will be the biggest problem, and if we keep the wires short, probably not at problem on the slave side, but because you have turned the IC 180 degrees, I think the power can turn out to be a issue in combination with the pullup's to I2C compliant level.  
I have made the new ones with side2 to the common I2C bus. Let's see if it makes the bus more stabile.
