### ISSUE TITLE
New PCB

### ISSUE THREAD

**Issue by tvixen** [stuartpittaway/diyBMS#9]
Hi Stuart

I made a new PCB for you. You can have a look and if its ok, approve it.  
This one is made with THT components, as many people don't have SMD in the drawer

Br Tim

**Comment by tvixen** [comment]
And here goes the files: 
[DIY BMSP Ver 3.0 brd .pdf](https://github.com/stuartpittaway/diyBMS/files/2188281/DIY.BMSP.Ver.3.0.brd.pdf)
[DIY BMSP Ver 3.0 sch .pdf](https://github.com/stuartpittaway/diyBMS/files/2188282/DIY.BMSP.Ver.3.0.sch.pdf)

**Comment by brunkj** [comment]
nice!  What is the physical dimensions of the board?

**Comment by tvixen** [comment]
78mm x 48mm

**Comment by stuartpittaway** [comment]
Nice work!  Do you need the capacitors on the inputs/outputs of the ADUM1250 module ?

**Comment by tvixen** [comment]
I would say, it depends of the length on side 2. But you will have a nicer risetime, and that might eliminate some i2c errors.
